import { Activity, Timer, Gauge, Server, CircleAlert, BarChart3, Network, HeartPulse, RefreshCw } from 'lucide-react';
import { useSuspenseQuery } from '@tanstack/react-query';
import { PageHeader } from '@/components/PageHeader';
import { StatusBadge } from '@/components/StatusBadge';
import { Button } from '@/components/ui/button';
import { platformService } from '@/services/platform';
export const metricsQuery={queryKey:['metrics'],queryFn:platformService.metrics};
export function Monitoring(){const {data:metrics,refetch,isFetching}=useSuspenseQuery(metricsQuery);
 const items=[{label:'Requests',key:'requests',icon:Activity},{label:'Latency',key:'latency',icon:Timer},{label:'Throughput',key:'throughput',icon:Gauge},{label:'Workers',key:'workers',icon:Server},{label:'Failures',key:'failures',icon:CircleAlert}] as const;
 return <main className="platform-page"><PageHeader eyebrow="PLATFORM / OBSERVABILITY" title="Monitoring" description="Platform health, inference performance, and distributed worker telemetry." action={<Button variant="outline" size="sm" disabled={isFetching} onClick={()=>refetch()}><RefreshCw className={isFetching?'animate-spin':''}/>Refresh</Button>}/><h2 className="section-heading">Platform Health</h2><div className="metric-strip">{items.map(m=><div key={m.label}><div className="metric-label">{m.label}<m.icon size={14}/></div><p className="metric-value">{metrics[m.key]??'—'}</p><span className="metric-sub">Not connected</span></div>)}</div><div className="charts-grid">{['Request Throughput','Latency','Worker Utilization','Request Distribution'].map((title,i)=><section className="chart-panel" key={title}><div className="chart-heading"><h2>{title}</h2><span>{['REQUESTS / SECOND','MILLISECONDS','PERCENT','BY CAPABILITY'][i]}</span></div><div className="empty-chart"><div><BarChart3 size={22}/><span>Waiting for backend</span></div></div><div className="chart-axis"><span>—</span><span>—</span><span>—</span><span>—</span><span>—</span></div></section>)}</div><h2 className="section-heading">Service Health</h2>{[['Orchestration service',Network],['Model serving',Server],['Health checks',HeartPulse]].map(([label,Icon])=>{const Symbol=Icon as typeof Server;return <div className="health-band" key={String(label)}><div><Symbol size={18}/><div><strong>{String(label)}</strong><small>Last received signal: —</small></div></div><StatusBadge/></div>;})}</main>;
}
